services:
  - type: web
    name: ansoyal-recruiter-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5002
      - key: STUDENT_API_URL
        value: https://intervexa.onrender.com/api/v1/recruiter
      - key: RECRUITER_SERVICE_SECRET
        value: ansoyal_recruiter_service_secret_secure_key_2026
